### ISSUE TITLE
mysql 

### ISSUE THREAD

**Issue by georgerahul24** [georgerahul24/Viraver1.1#3]
ability to add update and remove usernames and passwds

**Comment by thearavindh** [comment]
how can i run this code

**Comment by georgerahul24** [comment]
Hey, thank you for showing interest. But, in an effort to redesign the project, I had removed various dependiencies from PIP. Also, ELSA does not use MYSQL but, a custom file type for the same.

You can check the releases and see if you can run ELSA from there. The older versions of ELSA does not have any dependecies and can run standalone.
