### ISSUE TITLE
index files

### ISSUE THREAD

**Issue by georgerahul24** [georgerahul24/Viraver1.1#4]
ability to open files of indexed locations eg:index all the files in desktop so that given the file name it shld be opened

**Comment by georgerahul24** [comment]
- [ ] Make an indexer
- [ ] Implement indexer
- [ ] Implement cache

**Comment by PARTHAN27** [comment]
> 
> 
> ability to open files of indexed locations eg:index all the files in desktop so that given the file name it shld be opened

By this method that opening of download works r8? @georgerahul24

**Comment by georgerahul24** [comment]
> > 
> 
> > 
> 
> > ability to open files of indexed locations eg:index all the files in desktop so that given the file name it shld be opened
> 
> 
> 
> By this method that opening of download works r8? @georgerahul24 

Nope
#That opening of downloads folder work using this file

**Comment by georgerahul24** [comment]
This file is to open files....not folders 😄

**Comment by PARTHAN27** [comment]
> 
> 
> > > 
> > 
> > 
> > > 
> > 
> > 
> > > ability to open files of indexed locations eg:index all the files in desktop so that given the file name it shld be opened
> > 
> > 
> > By this method that opening of download works r8? @georgerahul24
> 
> Nope
> That opening of downloads folder work using tskver1file

wokay!!

**Comment by georgerahul24** [comment]
- [ ] Use python difflib or fuzzywuzzy to find the closest words

**Comment by georgerahul24** [comment]
Refer to the indexer.py file....

**Comment by georgerahul24** [comment]
completed in 51eb584f40c7fb8cf474859ed34021bfb5135715
